name: Auto Increment Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(cat version.txt 2>/dev/null || echo 0)
          echo "Current version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Increment version
        id: increment_version
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          NEW_VERSION=$((VERSION + 1))
          echo "New version: $NEW_VERSION"
          echo "::set-output name=new_version::$NEW_VERSION"
          echo $NEW_VERSION > version.txt

      - name: Get commit message
        id: get_commit_message
        run: |
          MESSAGE=$(git log -1 --pretty=%B)
          echo "Commit message: $MESSAGE"
          echo "::set-output name=message::$MESSAGE"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.increment_version.outputs.new_version }}
          release_name: Release v${{ steps.increment_version.outputs.new_version }}
          body: |
            ${{ steps.get_commit_message.outputs.message }}
          draft: false
          prerelease: false

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.txt
          git commit -m "Increment version to ${{ steps.increment_version.outputs.new_version }}"
          git push
